# configs/config.yaml
experiment:
  name: "GenMambaFlow_v1"
  device: "cuda"

data:
  root_dir: "./data"     # <--- 确保这里指向你的 data 文件夹路径
  image_size: 256
  batch_size: 4
  num_workers: 4

rqvae:
  embed_dim: 256
  codebook_size: 1024
  num_quantizers: 4
  learning_rate: 1.0e-4

gen_flow:
  in_channels: 3
  dim: 128
  secret_dim: 256
  learning_rate: 1.0e-4
  num_steps: 100000